### ISSUE TITLE
Interested in helping

### ISSUE THREAD

**Issue by miloofcroton** [Nexysweb/math-ts#13]
Hey, what's the status of this? I peered through the code and liked what I saw. Is there a level of polish that you want to hit or key features that you think are missing?

**Comment by johnb8005** [comment]
@miloofcroton so happy to read this! It is up to you really. The more people contribute the better! Happy to chat if needed

**Comment by johnb8005** [comment]
It's been a year and no answer. I'll close this. @miloofcroton if you're still interested, please reopen the task
